import type { Product } from "./types"

export const products: Product[] = [
  // Ice Cream
  {
    id: "1",
    name: "Strawberry Bliss Ice Cream",
    description: "Creamy strawberry ice cream made with fresh strawberries and premium cream",
    price: 450,
    salePrice: 350,
    discount: 22,
    image: "/placeholder.svg?height=300&width=300",
    category: "ice-cream",
    rating: 5,
    reviews: 124,
    onSale: true,
    popular: true,
  },
  {
    id: "2",
    name: "Chocolate Fudge Delight",
    description: "Rich chocolate ice cream with fudge swirls and chocolate chips",
    price: 500,
    image: "/placeholder.svg?height=300&width=300",
    category: "ice-cream",
    rating: 5,
    reviews: 98,
    popular: true,
  },
  {
    id: "3",
    name: "Vanilla Bean Supreme",
    description: "Classic vanilla ice cream with real vanilla bean specks",
    price: 400,
    image: "/placeholder.svg?height=300&width=300",
    category: "ice-cream",
    rating: 4,
    reviews: 87,
  },
  {
    id: "4",
    name: "Mint Chocolate Chip",
    description: "Refreshing mint ice cream with dark chocolate chips",
    price: 450,
    image: "/placeholder.svg?height=300&width=300",
    category: "ice-cream",
    rating: 4,
    reviews: 76,
  },
  {
    id: "5",
    name: "Caramel Popcorn Sundae",
    description: "Vanilla ice cream topped with caramel popcorn and sauce",
    price: 550,
    salePrice: 450,
    discount: 18,
    image: "/placeholder.svg?height=300&width=300",
    category: "ice-cream",
    rating: 5,
    reviews: 156,
    onSale: true,
    popular: true,
  },

  // Chocolates
  {
    id: "6",
    name: "Premium Dark Chocolate Box",
    description: "Assorted dark chocolates with various fillings and flavors",
    price: 1200,
    salePrice: 950,
    discount: 20,
    image: "/placeholder.svg?height=300&width=300",
    category: "chocolates",
    rating: 5,
    reviews: 156,
    onSale: true,
    popular: true,
  },
  {
    id: "7",
    name: "Milk Chocolate Truffles",
    description: "Smooth milk chocolate truffles dusted with cocoa powder",
    price: 950,
    image: "/placeholder.svg?height=300&width=300",
    category: "chocolates",
    rating: 5,
    reviews: 89,
    popular: true,
  },
  {
    id: "8",
    name: "White Chocolate Hearts",
    description: "Heart-shaped white chocolates perfect for special occasions",
    price: 800,
    image: "/placeholder.svg?height=300&width=300",
    category: "chocolates",
    rating: 4,
    reviews: 67,
  },
  {
    id: "9",
    name: "Chocolate Covered Strawberries",
    description: "Fresh strawberries dipped in premium chocolate",
    price: 1150,
    image: "/placeholder.svg?height=300&width=300",
    category: "chocolates",
    rating: 5,
    reviews: 134,
    popular: true,
  },

  // Flowers
  {
    id: "10",
    name: "Red Rose Bouquet",
    description: "Beautiful bouquet of 12 fresh red roses with baby's breath",
    price: 2300,
    image: "/placeholder.svg?height=300&width=300",
    category: "flowers",
    rating: 5,
    reviews: 203,
    popular: true,
  },
  {
    id: "11",
    name: "Mixed Spring Flowers",
    description: "Colorful arrangement of seasonal spring flowers",
    price: 1800,
    salePrice: 1500,
    discount: 17,
    image: "/placeholder.svg?height=300&width=300",
    category: "flowers",
    rating: 4,
    reviews: 145,
    onSale: true,
  },
  {
    id: "12",
    name: "White Lily Arrangement",
    description: "Elegant white lilies in a beautiful vase arrangement",
    price: 2650,
    image: "/placeholder.svg?height=300&width=300",
    category: "flowers",
    rating: 5,
    reviews: 78,
  },
  {
    id: "13",
    name: "Sunflower Bunch",
    description: "Bright and cheerful sunflowers to brighten any day",
    price: 1450,
    image: "/placeholder.svg?height=300&width=300",
    category: "flowers",
    rating: 4,
    reviews: 92,
    popular: true,
  },

  // Oreos & Cookies
  {
    id: "14",
    name: "Classic Oreo Cookies",
    description: "Original Oreo cookies with cream filling",
    price: 250,
    image: "/placeholder.svg?height=300&width=300",
    category: "oreos",
    rating: 5,
    reviews: 267,
    popular: true,
  },
  {
    id: "15",
    name: "Golden Oreo Cookies",
    description: "Golden vanilla cookies with cream filling",
    price: 250,
    image: "/placeholder.svg?height=300&width=300",
    category: "oreos",
    rating: 4,
    reviews: 189,
  },
  {
    id: "16",
    name: "Double Stuf Oreos",
    description: "Oreo cookies with double the cream filling",
    price: 300,
    image: "/placeholder.svg?height=300&width=300",
    category: "oreos",
    rating: 5,
    reviews: 234,
    popular: true,
  },
  {
    id: "17",
    name: "Oreo Thins",
    description: "Thin and crispy Oreo cookies",
    price: 225,
    salePrice: 200,
    discount: 11,
    image: "/placeholder.svg?height=300&width=300",
    category: "oreos",
    rating: 4,
    reviews: 156,
    onSale: true,
  },

  // Milk Products & Beverages
  {
    id: "18",
    name: "Fresh Whole Milk",
    description: "Farm-fresh whole milk in glass bottle",
    price: 350,
    image: "/placeholder.svg?height=300&width=300",
    category: "milk",
    rating: 5,
    reviews: 145,
    popular: true,
  },
  {
    id: "19",
    name: "Strawberry Milkshake",
    description: "Creamy strawberry milkshake with whipped cream and cherry",
    price: 450,
    image: "/placeholder.svg?height=300&width=300",
    category: "milk",
    rating: 5,
    reviews: 189,
    popular: true,
  },
  {
    id: "20",
    name: "Chocolate Milkshake",
    description: "Rich chocolate milkshake topped with whipped cream",
    price: 450,
    image: "/placeholder.svg?height=300&width=300",
    category: "milk",
    rating: 4,
    reviews: 167,
  },
  {
    id: "21",
    name: "Greek Yogurt",
    description: "Thick and creamy Greek yogurt, plain",
    price: 300,
    image: "/placeholder.svg?height=300&width=300",
    category: "milk",
    rating: 5,
    reviews: 167,
    popular: true,
  },
  {
    id: "22",
    name: "Artisan Cheese Selection",
    description: "Curated selection of artisan cheeses",
    price: 1650,
    salePrice: 1400,
    discount: 15,
    image: "/placeholder.svg?height=300&width=300",
    category: "milk",
    rating: 5,
    reviews: 89,
    onSale: true,
  },

  // Gift Items
  {
    id: "23",
    name: "Valentine's Gift Set",
    description: "Complete gift set with teddy bear, roses, and chocolates",
    price: 2500,
    salePrice: 2000,
    discount: 20,
    image: "/placeholder.svg?height=300&width=300",
    category: "gifts",
    rating: 5,
    reviews: 234,
    onSale: true,
    popular: true,
  },
  {
    id: "24",
    name: "Birthday Celebration Box",
    description: "Special birthday box with cake, balloons, and treats",
    price: 1800,
    image: "/placeholder.svg?height=300&width=300",
    category: "gifts",
    rating: 5,
    reviews: 156,
    popular: true,
  },
]
